version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      
      #- 433:433
    restart: always
    volumes:
      - ./nginx/robingather.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
      #- ./certbot/www:/var/www/certbot:ro
      #- ./certbot/conf:/etc/nginx/ssl:ro
      
    
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/www:/var/www/certbot:rw
  #     - ./certbot/conf:/etc/letsencrypt
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html

  # wp:
  #   build:
  #     context: .
  #     dockerfile: php.dockerfile
  #   volumes:
  #     - ./wordpress:/var/www/wordpress:delegated
  #   entrypoint: ['wp', '--allow-root']