upstream php {
    server unix:/tmp/php-cgi.socket;
    server php:9000;
}

server {
    listen 80;
    server_name dockertest.robingather.com;

    root /var/www/wordpress;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_intercept_errors on;
        fastcgi_pass php;
    }

}

# server {
#     listen 80;
#     listen [::]:80;

#     server_name dockertest.robingather.com;
#     server_tokens off;

#     location /.well-known/acme-challenge/ {
#         root /var/www/certbot;
#     }

#     location / {
#         return 301 https://dockertest.robingather.com$request_uri;
#     }
# }

# server {
#     listen 443 default_server ssl http2;
#     listen [::]:443 ssl http2;

#     server_name dockertest.robingather.com;

#     ssl_certificate /etc/nginx/ssl/live/example.org/fullchain.pem;
#     ssl_certificate_key /etc/nginx/ssl/live/example.org/privkey.pem;
    
#     index index.php

#     location / {
#         try_files $uri $uri/ /index.php?$args;
#     }

#     location ~ \.php$ {
#         include fastcgi.conf;
#         fastcgi_intercept_errors on;
#         fastcgi_pass php;
#     }
# }